# Generated by Django 5.0.4 on 2024-05-13 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company_name', models.CharField(max_length=255)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Shipping company',
                'verbose_name_plural': 'Shipping companies',
            },
        ),
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_delivery_date', models.DateTimeField(auto_now_add=True)),
                ('finish_delivery_date', models.DateTimeField(default=None, null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PREPARING', 'Preparing'), ('IN_TRANSIT', 'In transit'), ('ARRIVED', 'Arrived'), ('ON_THE_WAY', 'On the way'), ('DELIVERED', 'Delivered')], default='PREPARING', max_length=20)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.address')),
                ('delivery_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('shipping_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.shipping')),
            ],
        ),
    ]
