# Generated by Django 5.0.4 on 2024-05-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliveryinformation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinformation',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('IN_TRANSIT', 'In transit'), ('ARRIVED', 'Arrived'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered')], default='PREPARING', max_length=20),
        ),
    ]
