# Generated by Django 5.0.4 on 2024-05-23 16:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_address_options'),
        ('delivery', '0003_alter_deliveryinformation_status'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryInformation',
            new_name='Shipment',
        ),
    ]
