# Generated by Django 5.0.4 on 2024-05-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed')], max_length=20)),
                ('usage_type', models.CharField(choices=[('ORDER', 'Order'), ('DELIVERY', 'Delivery')], max_length=20)),
                ('usage_limit', models.IntegerField()),
                ('expiration_date', models.DateField()),
                ('min_order_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_customer_rank', models.IntegerField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold'), (3, 'Platinum'), (4, 'Diamond')], default=0)),
            ],
        ),
    ]
