# Generated by Django 5.0.4 on 2024-05-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='usage_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('DELIVERY', 'Delivery')], default='ORDER', max_length=20),
            preserve_default=False,
        ),
    ]
