# Generated by Django 5.0.4 on 2024-05-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_coupon_usage_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='minimum_order_value',
            new_name='min_order_value',
        ),
    ]
