# Generated by Django 5.0.4 on 2024-05-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(choices=[(0, 'Bronze'), (1, 'Silver'), (2, 'Gold'), (3, 'Platinum'), (4, 'Diamond')], default=0),
        ),
    ]
