# Generated by Django 5.0.4 on 2024-05-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='commune',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
