# Generated by Django 5.0.4 on 2024-05-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publisher', models.CharField(max_length=100)),
                ('edition', models.IntegerField()),
                ('be_sold', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
