# Generated by Django 5.0.4 on 2024-05-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupon_type'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinformation',
            name='start_delivery_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ManyToManyField(to='coupons.coupon'),
        ),
    ]
