# Generated by Django 5.0.4 on 2024-05-09 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_deliveryinformation_start_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_company_name', models.CharField(max_length=255)),
                ('shipping_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='deliveryinformation',
            name='shipping_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.shipping'),
        ),
    ]
