# Generated by Django 5.0.4 on 2024-05-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shipping_alter_deliveryinformation_shipping_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping',
            options={'verbose_name': 'Shipping company', 'verbose_name_plural': 'Shipping companies'},
        ),
    ]
