# Generated by Django 5.0.4 on 2024-05-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_rename_minimum_order_value_coupon_min_order_value'),
        ('orders', '0004_alter_shipping_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ManyToManyField(blank=True, null=True, to='coupons.coupon'),
        ),
    ]
