# Generated by Django 5.0.4 on 2024-05-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0004_rename_minimum_order_value_coupon_min_order_value'),
        ('orders', '0005_alter_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coupon',
            field=models.ManyToManyField(to='coupons.coupon'),
        ),
    ]
