name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.10]

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-decouple
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo "DEBUG=True" > .env
        echo "SECRET_KEY=your_secret_key_here" >> .env
        echo "DB_ENGINE=django.db.backends.mysql" >> .env
        echo "DB_NAME=test_db" >> .env
        echo "DB_USER=user" >> .env
        echo "DB_PASSWORD=password" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
    - name: Set up MySQL
      run: |
        sudo apt-get install -y default-libmysqlclient-dev
    - name: Run Migrations
      run: |
        python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: 3.10
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-decouple
        pip install -r requirements.txt
    - name: Create .env file
      run: |
        echo "DEBUG=True" > .env
        echo "SECRET_KEY=your_secret_key_here" >> .env
        echo "DB_ENGINE=django.db.backends.mysql" >> .env
        echo "DB_NAME=test_db" >> .env
        echo "DB_USER=user" >> .env
        echo "DB_PASSWORD=password" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "ALLOWED_HOSTS=localhost,127.0.0.1" >> .env
    - name: Deploy to Production
      run: |
        # Add your deployment commands here
        echo "Deploying to production"
